// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoSUkilsO-UmAg1v5riFYAyYh5HIc_Smw',
    appId: '1:334103106269:web:5d38441b96e423ed3bc134',
    messagingSenderId: '334103106269',
    projectId: 'social-media-app-d11ab',
    authDomain: 'social-media-app-d11ab.firebaseapp.com',
    storageBucket: 'social-media-app-d11ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRe4GjAykZpAgot4wonV5_YRIka7ZZ2oA',
    appId: '1:334103106269:android:2733d0697e4e4a0f3bc134',
    messagingSenderId: '334103106269',
    projectId: 'social-media-app-d11ab',
    storageBucket: 'social-media-app-d11ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0JaNR5Fc2SCZxzcVuKmkCVWGaq03BypE',
    appId: '1:334103106269:ios:055f88ca10830e103bc134',
    messagingSenderId: '334103106269',
    projectId: 'social-media-app-d11ab',
    storageBucket: 'social-media-app-d11ab.appspot.com',
    iosClientId: '334103106269-eo47e6q4kfahkddm70hapvm1nohhultf.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMeadiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0JaNR5Fc2SCZxzcVuKmkCVWGaq03BypE',
    appId: '1:334103106269:ios:94d96c573fcb7daf3bc134',
    messagingSenderId: '334103106269',
    projectId: 'social-media-app-d11ab',
    storageBucket: 'social-media-app-d11ab.appspot.com',
    iosClientId: '334103106269-il43iu8ptrnpr6paigj9l6q77b2bouph.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMeadiaApp.RunnerTests',
  );
}
